name: CI with Docker compose

on:
  pull_request:
    branches:
      - main
    push:
      branches:
        -main

jobs:
  test:
    runs-on: ubuntu-lastest

    steps:
      #Step 1: Check out the code
      - name: checkout repository
        uses: actions/checkout@v3

      #Step 2: Set up docker compose
      - name: Start services with Docker Compose
        run: docker compose up --build --abort-on-container-exit

      #Step3: Tear down services
      - name: Stop and clean up Docker Compose
        if: always()
        run: docker compose down 